/* data.js — static protocol, status and educational data */
window.PF = window.PF || {};
PF.data = {
  stages: [
    {
      id: "dns",
      name: "DNS",
      icon: "◎",
      base: 500,
      status: "RESOLVING DNS",
      proto: "DNS",
      layer: "Application",
      nums: [7],
      what: "Your browser needs to find the server's IP address.",
      why: "Computers route traffic by IP address, not by domain name. DNS translates one into the other.",
    },
    {
      id: "tcp",
      name: "TCP",
      icon: "⇄",
      base: 800,
      status: "CONNECTING TCP",
      proto: "TCP",
      layer: "Transport",
      nums: [4, 3],
      what: "Client and server run a three-way handshake: SYN, SYN-ACK, ACK.",
      why: "HTTP needs a reliable, ordered byte stream. TCP provides it, so a connection is established first.",
    },
    {
      id: "tls",
      name: "TLS",
      icon: "🔒︎",
      base: 900,
      status: "NEGOTIATING TLS",
      proto: "TLS 1.3",
      layer: "Presentation",
      nums: [6],
      what: "Both sides agree on keys and the client checks the server certificate.",
      why: "Without encryption, anyone on the path could read or modify the request. TLS gives confidentiality and integrity.",
    },
    {
      id: "http",
      name: "HTTP",
      icon: "→",
      base: 700,
      status: "SENDING REQUEST",
      proto: "HTTP",
      layer: "Application",
      nums: [7],
      what: "The request line, headers and optional body are sent to the server.",
      why: "HTTP is the application protocol that defines what you are asking for and how.",
    },
    {
      id: "server",
      name: "SERVER",
      icon: "▣",
      base: 1000,
      status: "PROCESSING",
      proto: "HTTP (server side)",
      layer: "Application",
      nums: [7],
      what: "The server parses, routes and handles the request (simulated here).",
      why: "The server must decide what resource you want and produce a response. Its time shows up as TTFB.",
    },
    {
      id: "response",
      name: "RESPONSE",
      icon: "←",
      base: 600,
      status: "RECEIVING RESPONSE",
      proto: "HTTP",
      layer: "Application",
      nums: [7],
      what: "Status line, headers and body travel back to the browser.",
      why: "The status code tells the client whether the request worked; headers and body carry the result.",
    },
  ],
  serverSteps: [
    "REQUEST RECEIVED",
    "Parsing request…",
    "Routing…",
    "Application logic…",
    "Database / service layer…",
    "Preparing response…",
  ],
  osi: [
    {
      n: 7,
      name: "Application",
      protos: "HTTP / HTTPS / DNS",
      purpose: "Protocols that applications use directly.",
      where: "HTTP request/response and DNS lookups.",
    },
    {
      n: 6,
      name: "Presentation",
      protos: "TLS / Encryption",
      purpose: "Data formatting, encoding, encryption.",
      where:
        "TLS handshake (TLS is often placed here, though it does not map cleanly).",
    },
    {
      n: 5,
      name: "Session",
      protos: "Session management",
      purpose: "Starting, maintaining and ending sessions.",
      where: "Conceptual: the persistent connection between client and server.",
    },
    {
      n: 4,
      name: "Transport",
      protos: "TCP / UDP",
      purpose: "End-to-end delivery, ports, reliability.",
      where: "TCP handshake and the byte stream carrying HTTP.",
    },
    {
      n: 3,
      name: "Network",
      protos: "IP",
      purpose: "Addressing and routing between networks.",
      where: "IP packets carrying every stage to the server IP.",
    },
    {
      n: 2,
      name: "Data Link",
      protos: "Ethernet / Wi-Fi",
      purpose: "Frames between directly connected nodes.",
      where: "Your local hop to the router (not visible here).",
    },
    {
      n: 1,
      name: "Physical",
      protos: "Signals / Radio",
      purpose: "Bits as electrical, optical or radio signals.",
      where: "The cable or radio link (not visible here).",
    },
  ],
  tcpip: [
    {
      name: "Application",
      protos: "HTTP / HTTPS / DNS",
      nums: [7, 6, 5],
      purpose: "Covers OSI layers 5–7.",
      where: "HTTP, TLS and DNS all live here in TCP/IP terms.",
    },
    {
      name: "Transport",
      protos: "TCP / UDP",
      nums: [4],
      purpose: "Same as OSI layer 4.",
      where: "TCP handshake.",
    },
    {
      name: "Internet",
      protos: "IP",
      nums: [3],
      purpose: "Same as OSI layer 3.",
      where: "IP routing.",
    },
    {
      name: "Network Access",
      protos: "Ethernet / Wi-Fi",
      nums: [2, 1],
      purpose: "Covers OSI layers 1–2.",
      where: "Local link.",
    },
  ],
  mapping:
    "TCP/IP collapses OSI layers 5–7 into Application and layers 1–2 into Network Access.",
  status: [
    [200, "OK", "The request succeeded.", "GET /users returns the list."],
    [
      201,
      "Created",
      "A new resource was created.",
      "POST /users creates a user.",
    ],
    [204, "No Content", "Success with no response body.", "DELETE /users/1."],
    [
      301,
      "Moved Permanently",
      "Resource has a new permanent URL.",
      "http:// redirecting to https://.",
    ],
    [302, "Found", "Temporary redirect.", "Redirect to a login page."],
    [
      304,
      "Not Modified",
      "Cached copy is still valid.",
      "Conditional GET with If-None-Match.",
    ],
    [
      400,
      "Bad Request",
      "The server cannot parse the request.",
      "Malformed JSON body.",
    ],
    [
      401,
      "Unauthorized",
      "Authentication is missing or invalid.",
      "No or bad Bearer token.",
    ],
    [
      403,
      "Forbidden",
      "Authenticated, but not allowed.",
      "Accessing another user’s data.",
    ],
    [404, "Not Found", "No resource at this URL.", "GET /users/99999."],
    [
      408,
      "Request Timeout",
      "Server timed out waiting for the request.",
      "Very slow upload.",
    ],
    [
      429,
      "Too Many Requests",
      "Rate limit exceeded.",
      "API quota reached; see Retry-After.",
    ],
    [
      500,
      "Internal Server Error",
      "Unhandled server-side failure.",
      "Uncaught exception in a handler.",
    ],
    [
      502,
      "Bad Gateway",
      "A gateway got an invalid upstream response.",
      "Proxy cannot reach the app.",
    ],
    [
      503,
      "Service Unavailable",
      "Server is overloaded or down.",
      "Maintenance window.",
    ],
    [
      504,
      "Gateway Timeout",
      "Upstream did not answer in time.",
      "Slow backend behind a load balancer.",
    ],
  ],
  statusCats: {
    1: "1xx Informational",
    2: "2xx Success",
    3: "3xx Redirection",
    4: "4xx Client Error",
    5: "5xx Server Error",
  },
  tcpudp: {
    TCP: {
      points:
        "Connection-oriented · Reliable · Ordered · Flow control · Congestion control",
      examples: "HTTPS, SSH, FTP",
      more: "TCP retransmits lost segments and reorders data, at the cost of handshake latency and head-of-line blocking.",
    },
    UDP: {
      points:
        "Connectionless · Lightweight · No ordering guarantee · Minimal overhead · No built-in congestion control",
      examples: "DNS, VoIP, gaming, streaming",
      more: "UDP just sends datagrams. Applications (or protocols like QUIC) add reliability themselves if needed.",
    },
  },
  dns: [
    [
      "Browser Cache",
      "The browser checks its own recent lookups first. Fastest path.",
    ],
    [
      "OS Cache",
      "The operating system resolver cache (and hosts file) is checked next.",
    ],
    [
      "DNS Resolver",
      "Usually your ISP or a public resolver. It recursively finds the answer and caches it.",
    ],
    [
      "Root",
      "Root servers do not know the IP, but know which TLD servers to ask (e.g. .com).",
    ],
    [
      "TLD",
      "The TLD server points to the authoritative name servers for the domain.",
    ],
    [
      "Authoritative DNS",
      "Holds the actual records for the domain, such as the A record.",
    ],
    [
      "IP",
      "The resolver returns the IP address; the browser can now open a TCP connection.",
    ],
  ],
  http: {
    "HTTP/1.1":
      "Text-based. Often uses multiple connections. Suffers head-of-line blocking per connection.",
    "HTTP/2":
      "Binary framing, multiplexing many streams over one connection, header compression (HPACK).",
    "HTTP/3":
      "Runs over QUIC (UDP-based). Faster connection setup and no TCP head-of-line blocking.",
  },
  presets: [
    {
      name: "Example.com",
      method: "GET",
      url: "https://example.com",
      headers: {},
    },
    {
      name: "JSONPlaceholder GET",
      method: "GET",
      url: "https://jsonplaceholder.typicode.com/posts/1",
      headers: { Accept: "application/json" },
    },
    {
      name: "JSONPlaceholder POST",
      method: "POST",
      url: "https://jsonplaceholder.typicode.com/posts",
      headers: { "Content-Type": "application/json" },
      body: '{\n  "title": "PingPong",\n  "body": "hello",\n  "userId": 1\n}',
    },
    {
      name: "HTTPBin GET",
      method: "GET",
      url: "https://httpbin.org/get",
      headers: { Accept: "application/json" },
    },
    {
      name: "GitHub API",
      method: "GET",
      url: "https://api.github.com/repos/torvalds/linux",
      headers: { Accept: "application/vnd.github+json" },
    },
  ],
};
